#################
# Fill in the scout name, date, and uncomment up to 22 merit badges
#######
$scout_name="First Last"
$date="April 27, 2013"
$badges = [
	 'camping',
	 'cit_community',
	 'cit_nation',
	 'cit_world',
	 'commcations',
	# 'emergency_preparedness',
	# 'life_saving',
	 'environmental_science',
	 'first_aid',
	# 'cyclingg',
	# 'cyclings',
	# 'hiking',
	# 'hikingg',
	# 'swimming',
	 'personal_management',
	 'personal_fitness',
	 'family_life',
	# 'american_business',
	# 'american_culture',
	# 'american_heritage',
	# 'american_labor',
	# 'animal_science',
	# 'archaeology',
	# 'archery',
	# 'architecture',
	# 'art',
	# 'astronomy',
	# 'athlete',
	# 'atomic_energy',
	# 'auto_mechanics',
	# 'aviation',
	# 'backpacking',
	# 'basketry',
	# 'bird_study',
	# 'bugling',
	# 'canoeing',
	# 'chemestry',
	# 'cinematography',
	# 'climbing',
	# 'coin_collecting',
	# 'collections',
	# 'computer',
	# 'cooking',
	# 'denistry',
	# 'disabilt',
	# 'dog_care',
	# 'drafting',
	# 'electricity',
	# 'electronics',
	# 'energy',
	# 'engineering',
	# 'entrepeneurship',
	# 'farm_mechanics',
	# 'fingerprinting',
	# 'fire_safety',
	# 'fishing',
	# 'fish_and_wildlife',
	# 'forestry',
	# 'gardening',
	# 'geneolog',
	# 'geology',
	# 'golf',
	# 'graphic_arts',
	# 'horsemanship',
	# 'indian_lore',
	# 'insects',
	# 'journalism',
	# 'landscape_archetecture',
	# 'law',
	# 'law_enforcement',
	# 'leatherwork',
	# 'mammal_study',
	# 'medicine',
	# 'metalwork',
	# 'model_design_building',
	# 'motorboating',
	# 'music',
	# 'nature',
	# 'nuclear_science',
	# 'oceanography',
	# 'orienteering',
	# 'painting',
	# 'pets',
	# 'photography',
	# 'pioneering',
	# 'plant_science',
	# 'plumbing',
	# 'pottery',
	# 'public_health',
	# 'public_speaking',
	# 'pulp_and_paper',
	# 'radio',
	# 'railroading',
	# 'reading',
	# 'reptile_amphibian_study',
	# 'rifle_shooting',
	# 'rowing',
	# 'safety',
	# 'salesmanship',
	# 'scholarship',
	# 'sculpture',
	# 'shotgun_shooting',
	# 'skating',
	# 'skiing',
	# 'small_boat_sailing',
	# 'soil_water_conservation',
	# 'space_exploration',
	# 'sports',
	# 'stamp_collecting',
	# 'surveying',
	# 'textile',
	# 'theater',
	# 'traffic_safety',
	# 'truck_transportation',
	# 'veterinary_medicine',
	# 'waterskiing',
	# 'weather',
	# 'whitewater',
	# 'wilderness_survival',
	# 'woodwork',
	# 'wood_carving'
]